import '../globals.css'
import { Inter } from 'next/font/google'
import { dir } from 'i18next'
import { languages } from '../i18n/settings'

const inter = Inter({ subsets: ['latin'] })

export async function generateStaticParams(){
  return languages.map((lng) => ({ lng }))
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: {
    lng
  }
}: {
  children: React.ReactNode,
  params: { lng: string }
}) {
  return (
    <html lang={lng} dir={dir(lng)}>
      <body className={`${inter.className} bg-green-200 lg:max-w-6xl mx-auto flex flex-col gap-6`}>
        {children}
      </body>
    </html>
  )
}
